apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    name: jenkins
spec:
  containers:
    - name: jenkins
      image: jenkins
      ports:
        - name: jenkins-port
          containerPort: 8080
