apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
    - name: mysql
      image: mysql:5.7
      ports:
        - name: dbserver 
          containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: 'Abhi@1996'    
