apiVersion: v1
kind: Pod
metadata:
  name: label-demo
  labels:
    environment: production
    stage: testing
    teams: infra-ops
  annotations:
    commit-id: 3190dd9e231b92f07da29e052a0fbc812ed8c999
    jira-issue: "https://jira.qualtitythought.in/issue/OP-25"
spec:
  containers:
  - name: label-demo
    image: httpd
    ports:
      - containerPort: 80
        protocol: TCP