apiVersion: v1
kind: Pod
metadata:
  name: huge-request
  labels:
    name: huge-request
spec:
  containers:
  - name: huge-request
    image: jenkins/jenkins
    resources:
      limits:
        memory: "128G"
        cpu: "24"
      requests:
        memory: "16G"
        cpu: "8"
    ports:
      - containerPort: 8080

