apiVersion: v1
kind: Pod 
metadata:
  name: resource-demo
  namespace: production
spec:
  containers:
    - name: webserver
      image: httpd 
      ports:
        - name: app
          containerPort: 80
          protocol: TCP
      resources: 
        limits:
          cpu: "1"
          memory: "512M"
        requests:
          cpu: "0.5"
          memory: "64M"
