apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 3
  minReadySeconds: 20
  selector:
    matchLabels:
      app: jenkins
      environment: production
      version: 1.60
  strategy:
    type: RollingUpdate 
    rollingUpdate: 
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      name: Jenkins-deployment
      labels:
        app: jenkins
        environment: production
        version: 1.60
    spec:
      containers:
        - name: jenkins
          image: jenkins:1.651.1
          ports:
            - containerPort: 8080
              protocol: TCP
