--- 
apiVersion: v1
kind: Pod  
metadata: 
  name: liveness-demo
  labels:
    environment: live
spec:
  restartPolicy: Never
  containers:
    - name: ubuntu-container
      image: ubuntu:latest
      command:
        - /bin/bash
        - ec 
        - touch /tmp/abhi; sleep 30; rm /tmp/abhi; sleep 300;
      livenessProbe: 
        exec:
          command:
            - cat 
            - tmp/abhi
        initialDelaySeconds: 2
        periodSeconds: 2