apiVersion: v1
kind: Pod 
metadata:
  name: liveness-with-always-restart
  namespace: production
spec:
  restartPolicy: Always
  containers:
    - name: liveness-with-always-restart
      image: ubuntu
      ports:
        - name: os
          containerPort: 80
          protocol: TCP
      resources: 
        limits:
          cpu: "1"
          memory: "512M"
        requests:
          cpu: "0.5"
          memory: "64M"
      command:
        - "/bin/bash"
        - "-ec"
        - "touch /tmp/abhi.txt; sleep 30; rm /tmp/abhi.txt" 
      livenessProbe:
        exec:
          command: 
            - "cat"
            - "/tmp/abhi.txt"
        initialDelaySeconds: 5
        periodSeconds: 5