apiVersion: v1
kind: Pod 
metadata:
  name: rediness-demo
  namespace: production
spec:
  restartPolicy: Always
  containers:
    - name: readiness-demo
      image: ubuntu
      ports:
        - name: os
          containerPort: 80
          protocol: TCP
      resources: 
        limits:
          cpu: "1"
          memory: "512M"
        requests:
          cpu: "0.5"
          memory: "64M"
      command:
        - "/bin/bash"
        - "-ec"
        - "sleep 30; touch /tmp/abhi.txt;" 
      readinessProbe:
        exec:
          command: 
            - "cat"
            - "/tmp/abhi.txt"
        initialDelaySeconds: 5
        periodSeconds: 5