--- 
apiVersion: v1
kind: Pod 
metadata:
  name: test 
  namespace: dev 
spec:
  containers: 
    - name: continuous integration
      image: jenkins/jenkins
      ports:
        - containerPorts: 8080
