--- 
apiVersion: v1
kind: Pod  
metadata: 
  name: liveness-demo
  labels:
    environment: live
spec:
  restartPolicy: Always
  containers:
    - name: ubuntu-container
      image: ubuntu:latest
      command:
        - /bin/bash
        - ec 
        - sleep 30; touch /tmp/ready; sleep 300;
      readinessProbe: 
        exec:
          command:
            - cat 
            - tmp/ready
        initialDelaySeconds: 10
        periodSeconds: 10